name: LaTeX Build

on:
  push:
    branches:
      - master  # Change this to match the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: lualatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: CV_Javier_EN.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: CV_EN
          release_name: Release CV_EN
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./CV_Javier_EN.pdf
          asset_name: CV_Javier_EN.pdf
          asset_content_type: pdf