name: LaTeX Build

on:
  push:
    branches:
      - master  # Change this to match the branch you want to trigger the build on

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Delete existing release
        id: delete_release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: CV
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: CV
          release_name: Release CV
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build-es:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build ES PDF
        uses: dante-ev/latex-action@latest
        with:
          root_file: CV_Javier_ES.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape

      - name: Upload ES PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ./CV_Javier_ES.pdf
          asset_name: CV_Javier_ES.pdf
          asset_content_type: application/pdf

      - name: Upload ES Lite PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ./CV_Javier_ES_lite.pdf
          asset_name: CV_Javier_ES_lite.pdf
          asset_content_type: application/pdf

  build-en:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build EN Lite Files
        run: python main.py --sections "None"
        
      - uses: actions/checkout@v2
      - name: Build EN lite PDF 
        uses: dante-ev/latex-action@latest
        with:
            root_file: CV_Javier_EN.tex
            compiler: lualatex
            args: -interaction=nonstopmode -shell-escape
            
      - name: Move EN Lite Files
        run: mv CV_Javier_EN.pdf ./CV_Javier_EN_lite.pdf

      - name: Upload EN Lite PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ./CV_Javier_EN_lite.pdf
          asset_name: CV_Javier_EN_lite.pdf
          asset_content_type: application/pdf

      - name: Build EN Full Version
        run: python main.py --sections "*"
        
      - uses: actions/checkout@v2
      - name: Build EN lite PDF 
        uses: dante-ev/latex-action@latest
        with:
            root_file: CV_Javier_EN.tex
            compiler: lualatex
            args: -interaction=nonstopmode -shell-escape

      - name: Upload EN Full PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ./CV_Javier_EN.pdf
          asset_name: CV_Javier_EN_full.pdf
          asset_content_type: application/pdf
