name: LaTeX Build

on:
  push:
    branches:
      - master  # Change this to match the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: lualatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: CV_Javier_EN.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
      # - name: main
      #   uses: dante-ev/latex-action@latest
      #   with:
      #     root_file: CV_Javier_EN.aux
      #     compiler: lualatex
      #     args: -interaction=nonstopmode -shell-escape
      # - name: lualatex main
      #   uses: dante-ev/latex-action@latest
      #   with:
      #     root_file: CV_Javier_EN.tex
      #     compiler: lualatex
      #     args: -interaction=nonstopmode -shell-escape