name: LaTeX Build

on:
  push:
    branches:
      - master  # Change this to match the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV_Javier_EN.tex  # Replace with your main LaTeX file name

      - name: Build LaTeX
        run: pdflatex -interaction=nonstopmode -halt-on-error CV_Javier_EN.tex  # Replace with your main LaTeX file name

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CV_Javier_EN.pdf  # Replace with your output PDF file name
          path: CV_Javier_EN.pdf  # Replace with the actual path to your output PDF file
