name: LaTeX Build

on:
  push:
    branches:
      - master  # Change this to match the branch you want to trigger the build on

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Delete existing release
        id: delete_release
        uses: dev-drprasad/delete-tag-and-release@v1.0.1  # Updated to latest stable version
        with:
          tag_name: CV
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1  # Using more maintained alternative
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: CV
          name: Release CV
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build-es:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build ES PDF
        uses: dante-ev/latex-action@latest
        with:
          root_file: CV_Javier_ES.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape

      - name: Upload ES PDF
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: CV
          files: CV_Javier_ES.pdf

  build-en:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.11'
          cache: 'pip'  # Added caching for pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build EN Lite Files
        run: python main.py --sections "None"
        
      - name: Build EN lite PDF 
        uses: dante-ev/latex-action@latest
        with:
          root_file: CV_Javier_EN.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
            
      - name: Move EN Lite Files
        run: mv CV_Javier_EN.pdf ./CV_Javier_EN_lite.pdf

      - name: Build EN Full Version
        run: python main.py --sections "*"
        
      - name: Build EN Full PDF 
        uses: dante-ev/latex-action@latest
        with:
          root_file: CV_Javier_EN.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape

      - name: Upload PDFs
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: CV
          files: |
            CV_Javier_EN_lite.pdf
            CV_Javier_EN.pdf
