name: LaTeX Build

on:
  push:
    branches:
      - master  # Change this to match the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest-

 steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: CV_Javier_EN.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: CV_Javier_EN.aux
          compiler: bibtex
          args: 
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: CV_Javier_EN.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape